### ISSUE TITLE
纠错

### ISSUE THREAD

**Issue by shexuan** [YC-Coder-Chen/feature-engineering-handbook#1]
Notebook1 数据预处理 1.2.9节 有两个𝑑𝑖𝑠𝑡𝑟𝑖𝑏𝑢𝑡𝑖𝑜𝑛_𝑜𝑓_𝑝𝑜𝑠𝑖𝑡𝑖𝑣𝑒，其中一个应该是𝑑𝑖𝑠𝑡𝑟𝑖𝑏𝑢𝑡𝑖𝑜𝑛_𝑜𝑓_negative才对？

**Comment by YC-Coder-Chen** [comment]
哈罗，谢谢你指出了这个问题，这个的确是一个Typo，我现在fix这个问题。

**Comment by shexuan** [comment]
> 哈罗，谢谢你指出了这个问题，这个的确是一个Typo，我现在fix这个问题。

嗯 感谢分享知识才是
